package statusline

import (
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

// The testdata/*.golden bytes are the byte-fidelity source of truth: each was
// minted ONCE from the reference node statusline (~/.claude/hooks/statusline.js)
// by testdata/mint.sh under a PINNED sandbox and committed. These tests read only
// the committed bytes and NEVER invoke node.
//
// generated by: sh internal/statusline/testdata/mint.sh ~/.claude/hooks/statusline.js
//   sandbox env per case (see mint.sh): CLAUDE_CONFIG_DIR=<empty temp dir> (no
//   todos/jobs => line 2 is the meter only, never a line 3); CLAUDE_JOB_DIR unset;
//   CLAUDE_CODE_AUTO_COMPACT_WINDOW pinned per meter case; stdin JSON carries
//   model.display_name, workspace.current_dir (/work/myproject => branch "" and no
//   .dross up-walk; the *_branch case uses a `git init -b main` repo named
//   "myproject" => branch "main"), and context_window.{total_tokens,remaining_percentage}.
// The Inputs in each table row below mirror exactly the stdin/env that minted its golden.

func fptr(v float64) *float64 { return &v }

func readGolden(t *testing.T, name string) []byte {
	t.Helper()
	b, err := os.ReadFile(filepath.Join("testdata", name+".golden"))
	if err != nil {
		t.Fatalf("read golden %s: %v (run testdata/mint.sh to regenerate)", name, err)
	}
	return b
}

// renderCases pair a committed golden with the Inputs that minted it.
var renderCases = []struct {
	golden string
	in     Inputs
}{
	// Line 1 only (no context_window => no meter).
	{"line1_plain", Inputs{Model: "Claude", Dir: "/work/myproject"}},
	{"line1_branch", Inputs{Model: "Claude", Dir: "/work/myproject", Branch: "main"}},

	// Context-meter band edges, auto-compact window 200000 / total 1_000_000 (a
	// clean 20% buffer) so remaining maps onto used% 49/50/64/65/79/80.
	{"meter_u49", Inputs{Model: "Claude", Dir: "/work/myproject", RemainingPercent: fptr(60.8), TotalTokens: 1_000_000, AutoCompactWindow: 200000}},
	{"meter_u50", Inputs{Model: "Claude", Dir: "/work/myproject", RemainingPercent: fptr(60.0), TotalTokens: 1_000_000, AutoCompactWindow: 200000}},
	{"meter_u64", Inputs{Model: "Claude", Dir: "/work/myproject", RemainingPercent: fptr(48.8), TotalTokens: 1_000_000, AutoCompactWindow: 200000}},
	{"meter_u65", Inputs{Model: "Claude", Dir: "/work/myproject", RemainingPercent: fptr(48.0), TotalTokens: 1_000_000, AutoCompactWindow: 200000}},
	{"meter_u79", Inputs{Model: "Claude", Dir: "/work/myproject", RemainingPercent: fptr(36.8), TotalTokens: 1_000_000, AutoCompactWindow: 200000}},
	{"meter_u80", Inputs{Model: "Claude", Dir: "/work/myproject", RemainingPercent: fptr(36.0), TotalTokens: 1_000_000, AutoCompactWindow: 200000}},

	// Auto-compact normalization variants.
	{"meter_default", Inputs{Model: "Claude", Dir: "/work/myproject", RemainingPercent: fptr(60.0), TotalTokens: 1_000_000, AutoCompactWindow: 0}},           // ~16.5% default buffer
	{"meter_total_override", Inputs{Model: "Claude", Dir: "/work/myproject", RemainingPercent: fptr(60.0), TotalTokens: 500_000, AutoCompactWindow: 200000}}, // buffer 200000/500000 => 40%

	// Line-2 body: todo (bold) wins over dross state (dim), each crossed with the
	// meter present/absent. The gather layer pre-formats DrossState; render dims it.
	{"todo_only", Inputs{Model: "Claude", Dir: "/work/myproject", TodoActiveForm: "Doing the thing"}},
	{"todo_with_meter", Inputs{Model: "Claude", Dir: "/work/myproject", TodoActiveForm: "Doing the thing", RemainingPercent: fptr(60.0), TotalTokens: 1_000_000, AutoCompactWindow: 200000}},
	{"state_only", Inputs{Model: "Claude", Dir: "/x/proj", DrossState: "v0.8 · native-statusline · planned"}},
	{"state_with_meter", Inputs{Model: "Claude", Dir: "/x/proj", DrossState: "v0.8 · native-statusline · planned", RemainingPercent: fptr(60.0), TotalTokens: 1_000_000, AutoCompactWindow: 200000}},
	{"state_missing_field", Inputs{Model: "Claude", Dir: "/x/projpartial", DrossState: "v0.8 · native-statusline"}},
	{"todo_wins", Inputs{Model: "Claude", Dir: "/x/proj", TodoActiveForm: "Doing the thing", DrossState: "v0.8 · native-statusline · planned"}},
}

// TestRender pins the full render output byte-for-byte against the node-minted
// goldens. A drift in line-1 layout, an ANSI code, the dim wrappers, the ⎇ branch
// segment, the meter math, or the leading-space strip fails here.
func TestRender(t *testing.T) {
	for _, c := range renderCases {
		t.Run(c.golden, func(t *testing.T) {
			got := Render(c.in)
			want := readGolden(t, c.golden)
			if string(got) != string(want) {
				t.Errorf("Render mismatch for %s\n got: %q\nwant: %q", c.golden, got, want)
			}
		})
	}
}

// TestContextMeterBands asserts the band selection and the Math.floor(used/10) cell
// fill explicitly at every threshold edge, on top of the byte-equality in TestRender
// — so a regression that swaps a color or miscounts cells localizes to the meter.
func TestContextMeterBands(t *testing.T) {
	cases := []struct {
		golden string
		used   int
		sgr    string // exact leading SGR escape for the band
	}{
		{"meter_u49", 49, "\x1b[32m"},       // green   <50
		{"meter_u50", 50, "\x1b[33m"},       // yellow  <65
		{"meter_u64", 64, "\x1b[33m"},       // yellow  <65
		{"meter_u65", 65, "\x1b[38;5;208m"}, // orange  <80
		{"meter_u79", 79, "\x1b[38;5;208m"}, // orange  <80
		{"meter_u80", 80, "\x1b[5;31m"},     // blinking red >=80
	}
	for _, c := range cases {
		t.Run(c.golden, func(t *testing.T) {
			out := string(readGolden(t, c.golden))
			if !strings.Contains(out, c.sgr) {
				t.Errorf("%s: missing band SGR %q in %q", c.golden, c.sgr, out)
			}
			pct := strconv.Itoa(c.used) + "%"
			if !strings.Contains(out, pct) {
				t.Errorf("%s: missing %q in %q", c.golden, pct, out)
			}
			if c.used >= 80 && !strings.Contains(out, "💀") {
				t.Errorf("%s: expected blinking 💀 at used>=80, got %q", c.golden, out)
			}
			if gotFilled := strings.Count(out, "█"); gotFilled != c.used/10 {
				t.Errorf("%s: filled cells = %d, want floor(%d/10) = %d", c.golden, gotFilled, c.used, c.used/10)
			}
		})
	}
}

// TestRenderLine2 pins the byte-fragile line-2 assembly: todo precedence and the
// context-meter leading-space rule (kept as a separator after a body, stripped when
// the body is empty — the reference's ctxOnLine2 branch).
func TestRenderLine2(t *testing.T) {
	// Todo wins over state: bold todo present, the state string absent entirely.
	out := string(Render(Inputs{Model: "Claude", Dir: "/x/proj", TodoActiveForm: "Doing the thing", DrossState: "v0.8 · native-statusline · planned"}))
	if !strings.Contains(out, "\x1b[1mDoing the thing\x1b[0m") {
		t.Errorf("todo-wins: missing bold todo in %q", out)
	}
	if strings.Contains(out, "native-statusline") {
		t.Errorf("todo-wins: dross state leaked into output %q", out)
	}

	// Body present + meter: the meter keeps its leading space as a separator, so the
	// reset of the body is followed by " " then the meter SGR.
	body := string(Render(Inputs{Model: "Claude", Dir: "/x/proj", DrossState: "v0.8 · p · s", RemainingPercent: fptr(60.0), TotalTokens: 1_000_000, AutoCompactWindow: 200000}))
	line2 := strings.Split(body, "\n")[1]
	if !strings.HasPrefix(line2, "\x1b[2mv0.8 · p · s\x1b[0m \x1b[") {
		t.Errorf("body+meter: want '<dim state><reset> <meter>', got %q", line2)
	}

	// No body + meter: the meter's leading space is stripped, so line 2 starts with
	// the meter SGR directly (no stray leading space).
	noBody := string(Render(Inputs{Model: "Claude", Dir: "/x/proj", RemainingPercent: fptr(60.0), TotalTokens: 1_000_000, AutoCompactWindow: 200000}))
	mline := strings.Split(noBody, "\n")[1]
	if strings.HasPrefix(mline, " ") {
		t.Errorf("no-body+meter: stray leading space before meter: %q", mline)
	}
	if !strings.HasPrefix(mline, "\x1b[") {
		t.Errorf("no-body+meter: line 2 should start with the meter SGR, got %q", mline)
	}
}

// TestContextMeterAbsent: a nil RemainingPercent yields no meter at all (line 1
// only), matching the reference's "absent when remaining_percentage is not provided".
func TestContextMeterAbsent(t *testing.T) {
	in := Inputs{Model: "Claude", Dir: "/work/myproject"}
	if ctx := contextMeter(in); ctx != "" {
		t.Errorf("contextMeter with nil remaining = %q, want empty", ctx)
	}
	out := string(Render(in))
	if strings.Contains(out, "\n") {
		t.Errorf("Render with nil remaining should be line 1 only, got %q", out)
	}
}
