// Package ship implements /dross-ship: PR-body generation, branch
// filtering (drop .dross/), and provider-aware PR open against GitHub
// or Forgejo.
package ship

import (
	"fmt"
	"sort"
	"strings"

	"github.com/Rivil/dross/internal/phase"
	"github.com/Rivil/dross/internal/verify"
)

// BuildPRBody renders a markdown PR body from spec + verify. Both can
// be nil: a missing spec produces a minimal "phase X" header; a missing
// verify drops the efficacy section. The output is stable (no
// timestamps in the body) so re-shipping after a tweak generates a
// reproducible diff.
func BuildPRBody(spec *phase.Spec, v *verify.Verify) string {
	var b strings.Builder

	title := "phase"
	if spec != nil && spec.Phase.Title != "" {
		title = spec.Phase.Title
	}
	id := ""
	if spec != nil {
		id = spec.Phase.ID
	}
	if id != "" {
		fmt.Fprintf(&b, "# %s — %s\n\n", id, title)
	} else {
		fmt.Fprintf(&b, "# %s\n\n", title)
	}

	if spec != nil && len(spec.Criteria) > 0 {
		b.WriteString("## Acceptance criteria\n\n")
		// status lookup from verify
		statusByID := map[string]verify.CriterionResult{}
		if v != nil {
			for _, c := range v.Criteria {
				statusByID[c.ID] = c
			}
		}
		b.WriteString("| ID | Criterion | Status | Tests |\n")
		b.WriteString("|---|---|---|---|\n")
		for _, c := range spec.Criteria {
			r := statusByID[c.ID]
			status := r.Status
			if status == "" {
				status = "—"
			}
			tests := strings.Join(r.Tests, ", ")
			if tests == "" {
				tests = "—"
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n",
				c.ID, escapePipe(c.Text), status, escapePipe(tests))
		}
		b.WriteString("\n")
	}

	if spec != nil && len(spec.Decisions) > 0 {
		b.WriteString("## Decisions locked\n\n")
		for _, d := range spec.Decisions {
			lock := ""
			if d.Locked {
				lock = " 🔒"
			}
			fmt.Fprintf(&b, "- **%s**%s — %s",
				d.Key, lock, d.Choice)
			if d.Why != "" {
				fmt.Fprintf(&b, " *(%s)*", d.Why)
			}
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}

	if v != nil {
		b.WriteString("## Efficacy\n\n")
		s := v.Summary
		fmt.Fprintf(&b, "- Mutation score: **%.1f%%** (%d killed / %d survived)\n",
			s.MutationScore*100, s.MutantsKilled, s.MutantsSurvived)
		fmt.Fprintf(&b, "- Criteria coverage: **%d/%d** covered, %d uncovered\n",
			s.CriteriaCovered, s.CriteriaTotal, s.CriteriaUncovered)
		verdict := v.Verify.Verdict
		if verdict == "" {
			verdict = "pending"
		}
		fmt.Fprintf(&b, "- Verdict: **%s**\n\n", strings.ToUpper(verdict))

		if len(v.Findings) > 0 {
			b.WriteString("## Findings\n\n")
			// Sort by severity for predictability: BLOCKING first.
			ordered := append([]verify.Finding(nil), v.Findings...)
			sort.SliceStable(ordered, func(i, j int) bool {
				return severityRank(ordered[i].Severity) < severityRank(ordered[j].Severity)
			})
			for _, f := range ordered {
				sev := f.Severity
				if sev == "" {
					sev = "NOTE"
				}
				fmt.Fprintf(&b, "- **%s**: %s\n", sev, f.Text)
			}
			b.WriteString("\n")
		}
	}

	b.WriteString("---\n")
	b.WriteString("_Generated by `dross ship`. Edit before push if you want this body changed._\n")
	return b.String()
}

func severityRank(s string) int {
	switch strings.ToUpper(s) {
	case "BLOCKING":
		return 0
	case "FLAG":
		return 1
	case "NOTE", "":
		return 2
	default:
		return 3
	}
}

func escapePipe(s string) string {
	// Markdown table cells: pipe and newline must not appear raw.
	s = strings.ReplaceAll(s, "|", `\|`)
	s = strings.ReplaceAll(s, "\n", " ")
	return s
}
