// Package ship implements /dross-ship: PR-body generation, branch
// filtering (drop .dross/), and provider-aware PR open against GitHub
// or Forgejo.
package ship

import (
	"fmt"
	"sort"
	"strings"
	"unicode/utf8"

	"github.com/Rivil/dross/internal/changes"
	"github.com/Rivil/dross/internal/phase"
	"github.com/Rivil/dross/internal/verify"
)

// BuildPRBody renders a markdown PR body from spec + verify + the solo
// reviewer's per-task reviews (changes.json `reviews`). All can be nil: a
// missing spec produces a minimal "phase X" header; a missing verify drops
// the efficacy section; no reviews drops the reviewer section. The output is
// stable (no timestamps in the body) so re-shipping after a tweak generates a
// reproducible diff.
func BuildPRBody(spec *phase.Spec, v *verify.Verify, reviews map[string]changes.TaskReview) string {
	var b strings.Builder

	title := "phase"
	if spec != nil && spec.Phase.Title != "" {
		title = spec.Phase.Title
	}
	id := ""
	if spec != nil {
		id = spec.Phase.ID
	}
	if id != "" {
		fmt.Fprintf(&b, "# %s — %s\n\n", id, title)
	} else {
		fmt.Fprintf(&b, "# %s\n\n", title)
	}

	if spec != nil && len(spec.Criteria) > 0 {
		b.WriteString("## Acceptance criteria\n\n")
		// status lookup from verify
		statusByID := map[string]verify.CriterionResult{}
		if v != nil {
			for _, c := range v.Criteria {
				statusByID[c.ID] = c
			}
		}
		b.WriteString("| ID | Criterion | Status | Tests |\n")
		b.WriteString("|---|---|---|---|\n")
		for _, c := range spec.Criteria {
			r := statusByID[c.ID]
			status := r.Status
			if status == "" {
				status = "—"
			}
			tests := strings.Join(r.Tests, ", ")
			if tests == "" {
				tests = "—"
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n",
				c.ID, escapePipe(c.Text), status, escapePipe(tests))
		}
		b.WriteString("\n")
	}

	if spec != nil && len(spec.Decisions) > 0 {
		b.WriteString("## Decisions locked\n\n")
		for _, d := range spec.Decisions {
			lock := ""
			if d.Locked {
				lock = " 🔒"
			}
			fmt.Fprintf(&b, "- **%s**%s — %s",
				d.Key, lock, d.Choice)
			if d.Why != "" {
				fmt.Fprintf(&b, " *(%s)*", d.Why)
			}
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}

	if v != nil {
		b.WriteString("## Efficacy\n\n")
		s := v.Summary
		fmt.Fprintf(&b, "- Mutation score: **%.1f%%** (%d killed / %d survived)\n",
			s.MutationScore*100, s.MutantsKilled, s.MutantsSurvived)
		fmt.Fprintf(&b, "- Criteria coverage: **%d/%d** covered, %d uncovered\n",
			s.CriteriaCovered, s.CriteriaTotal, s.CriteriaUncovered)
		verdict := v.Verify.Verdict
		if verdict == "" {
			verdict = "pending"
		}
		fmt.Fprintf(&b, "- Verdict: **%s**\n\n", strings.ToUpper(verdict))

		if len(v.Findings) > 0 {
			b.WriteString("## Findings\n\n")
			// Sort by severity for predictability: BLOCKING first.
			ordered := append([]verify.Finding(nil), v.Findings...)
			sort.SliceStable(ordered, func(i, j int) bool {
				return severityRank(ordered[i].Severity) < severityRank(ordered[j].Severity)
			})
			for _, f := range ordered {
				sev := f.Severity
				if sev == "" {
					sev = "NOTE"
				}
				fmt.Fprintf(&b, "- **%s**: %s\n", sev, f.Text)
			}
			b.WriteString("\n")
		}
	}

	writeReviews(&b, reviews)

	b.WriteString("---\n")
	b.WriteString("_Generated by `dross ship`. Edit before push if you want this body changed._\n")
	return b.String()
}

// reviewSectionBudget bounds the reviewer section, well inside the 65,536
// characters a GitHub PR body may hold alongside the rest of the body.
const reviewSectionBudget = 30000

// reviewTextCap bounds one finding's text in the body; changes.json keeps it
// whole.
const reviewTextCap = 600

// writeReviews renders what the solo reviewer flagged (c-6): per task, in task
// order, its outcome and every finding with its resolution, one line each.
// Finding text is reviewer output — newlines and pipes are flattened so it can
// never open a heading or break a line, and the section stops at its budget
// with a count of what it dropped.
func writeReviews(b *strings.Builder, reviews map[string]changes.TaskReview) {
	if len(reviews) == 0 {
		return
	}
	ids := make([]string, 0, len(reviews))
	for id := range reviews {
		ids = append(ids, id)
	}
	sort.Slice(ids, func(i, j int) bool {
		if len(ids[i]) != len(ids[j]) {
			return len(ids[i]) < len(ids[j])
		}
		return ids[i] < ids[j]
	})

	var lines []string
	for _, id := range ids {
		r := reviews[id]
		head := fmt.Sprintf("- `%s` — %s after %d round%s", escapePipe(id), escapePipe(r.Outcome), r.Rounds, plural(r.Rounds))
		if r.Cause != "" {
			head += ": " + clip(escapePipe(r.Cause))
		}
		lines = append(lines, head)
		for _, f := range r.Findings {
			crit := ""
			if f.Criterion != "" {
				crit = " `" + escapePipe(f.Criterion) + "`"
			}
			lines = append(lines, fmt.Sprintf("  - **%s** %s%s (round %d): %s — _%s_",
				escapePipe(f.Severity), escapePipe(f.Kind), crit, f.Round, clip(escapePipe(f.Text)), escapePipe(f.Resolution)))
		}
	}

	b.WriteString("## Reviewer findings\n\n")
	used := 0
	for i, line := range lines {
		if used+len(line)+1 > reviewSectionBudget {
			dropped := 0
			for _, rest := range lines[i:] {
				if strings.HasPrefix(rest, "  - ") {
					dropped++
				}
			}
			fmt.Fprintf(b, "- … %d more finding%s in changes.json\n", dropped, plural(dropped))
			break
		}
		b.WriteString(line + "\n")
		used += len(line) + 1
	}
	b.WriteString("\n")
}

func clip(s string) string {
	if len(s) <= reviewTextCap {
		return s
	}
	cut := reviewTextCap
	for cut > 0 && !utf8.RuneStart(s[cut]) {
		cut--
	}
	return s[:cut] + "…"
}

func plural(n int) string {
	if n == 1 {
		return ""
	}
	return "s"
}

func severityRank(s string) int {
	switch strings.ToUpper(s) {
	case "BLOCKING":
		return 0
	case "FLAG":
		return 1
	case "NOTE", "":
		return 2
	default:
		return 3
	}
}

func escapePipe(s string) string {
	// Markdown table cells: pipe and newline must not appear raw.
	s = strings.ReplaceAll(s, "|", `\|`)
	s = strings.ReplaceAll(s, "\n", " ")
	return s
}
