package ship

import (
	"fmt"
	"regexp"
	"strings"
	"testing"

	"github.com/Rivil/dross/internal/changes"
	"github.com/Rivil/dross/internal/phase"
	"github.com/Rivil/dross/internal/verify"
)

func TestBuildPRBodyFullArtefacts(t *testing.T) {
	spec := &phase.Spec{
		Phase: phase.SpecPhase{ID: "01-meal-tagging", Title: "Meal Tagging System"},
		Criteria: []phase.Criterion{
			{ID: "C1", Text: "Tags can be added to meals"},
			{ID: "C2", Text: "Tags can be filtered by | and color"},
		},
		Decisions: []phase.Decision{
			{Key: "storage", Choice: "drizzle JSON column", Why: "avoids join complexity", Locked: true},
		},
	}
	v := &verify.Verify{
		Verify: verify.VerifyMeta{Phase: "01-meal-tagging", Verdict: "pass"},
		Summary: verify.VerifySummary{
			MutationScore:     0.873,
			MutantsKilled:     123,
			MutantsSurvived:   18,
			CriteriaTotal:     2,
			CriteriaCovered:   2,
			CriteriaUncovered: 0,
		},
		Criteria: []verify.CriterionResult{
			{ID: "C1", Status: "covered", Tests: []string{"meal.test.ts:42"}},
			{ID: "C2", Status: "covered", Tests: []string{"meal.test.ts:78", "filter.test.ts:11"}},
		},
		Findings: []verify.Finding{
			{Severity: "NOTE", Text: "tag color picker UI is basic"},
			{Severity: "BLOCKING", Text: "shouldn't merge"},
			{Severity: "FLAG", Text: "review threshold magic number"},
		},
	}

	body := BuildPRBody(spec, v, nil)

	for _, want := range []string{
		"# 01-meal-tagging — Meal Tagging System",
		"## Acceptance criteria",
		"| `C1` | Tags can be added to meals | covered | meal.test.ts:42 |",
		`Tags can be filtered by \| and color`, // pipe escaped
		"## Decisions locked",
		"- **storage** 🔒 — drizzle JSON column *(avoids join complexity)*",
		"## Efficacy",
		"Mutation score: **87.3%** (123 killed / 18 survived)",
		"Criteria coverage: **2/2** covered, 0 uncovered",
		"Verdict: **PASS**",
		"## Findings",
		"_Generated by `dross ship`",
	} {
		if !strings.Contains(body, want) {
			t.Errorf("expected %q in body\n--- body ---\n%s", want, body)
		}
	}

	// Findings ordered: BLOCKING before FLAG before NOTE.
	iBlock := strings.Index(body, "BLOCKING")
	iFlag := strings.Index(body, "FLAG")
	iNote := strings.Index(body, "NOTE")
	if !(iBlock < iFlag && iFlag < iNote) {
		t.Errorf("findings not severity-ordered: BLOCKING=%d FLAG=%d NOTE=%d", iBlock, iFlag, iNote)
	}
}

func TestBuildPRBodyMinimalSpec(t *testing.T) {
	spec := &phase.Spec{
		Phase: phase.SpecPhase{ID: "02-tiny", Title: "Tiny Phase"},
	}
	body := BuildPRBody(spec, nil, nil)
	if !strings.Contains(body, "# 02-tiny — Tiny Phase") {
		t.Errorf("missing header: %s", body)
	}
	if strings.Contains(body, "## Acceptance criteria") {
		t.Errorf("should not show criteria section without criteria: %s", body)
	}
	if strings.Contains(body, "## Efficacy") {
		t.Errorf("should not show efficacy without verify: %s", body)
	}
}

func TestBuildPRBodyNilSpec(t *testing.T) {
	body := BuildPRBody(nil, nil, nil)
	if !strings.Contains(body, "# phase") {
		t.Errorf("expected fallback header, got: %s", body)
	}
}

func TestBuildPRBodyHandlesUnverifiedCriterion(t *testing.T) {
	spec := &phase.Spec{
		Phase: phase.SpecPhase{ID: "03-x", Title: "X"},
		Criteria: []phase.Criterion{
			{ID: "C1", Text: "Should work"},
			{ID: "C2", Text: "Should also work"},
		},
	}
	v := &verify.Verify{
		Criteria: []verify.CriterionResult{
			{ID: "C1", Status: "covered", Tests: []string{"a.test.ts"}},
			// C2 has no result
		},
	}
	body := BuildPRBody(spec, v, nil)
	// C2 row must render with placeholder status.
	if !strings.Contains(body, "| `C2` | Should also work | — | — |") {
		t.Errorf("expected placeholder for unverified C2, got:\n%s", body)
	}
}

func TestBuildPRBodyStableOutput(t *testing.T) {
	// Same input → same output (no timestamps embedded).
	spec := &phase.Spec{
		Phase:    phase.SpecPhase{ID: "01-x", Title: "X"},
		Criteria: []phase.Criterion{{ID: "C1", Text: "ok"}},
	}
	a := BuildPRBody(spec, nil, nil)
	b := BuildPRBody(spec, nil, nil)
	if a != b {
		t.Errorf("expected stable output:\nA: %s\nB: %s", a, b)
	}
}

func sampleReviews() map[string]changes.TaskReview {
	return map[string]changes.TaskReview{
		"t-10": {Outcome: "exhausted", Rounds: 2, Cause: "still blocked after the one fix round", Findings: []changes.ReviewFinding{
			{Round: 2, Kind: "spec", Severity: "BLOCKING", Criterion: "c-3", Text: "no test drives two blocked rounds", Resolution: "unresolved — task failed"},
		}},
		"t-2": {Outcome: "pass", Rounds: 2, Findings: []changes.ReviewFinding{
			{Round: 1, Kind: "spec", Severity: "BLOCKING", Criterion: "c-1", Text: "pair skip untested", Resolution: "fixed in the fix round"},
			{Round: 1, Kind: "quality", Severity: "FLAG", Text: "long func", Resolution: "non-blocking, left"},
		}},
	}
}

func TestReviewSectionRenders(t *testing.T) {
	spec := &phase.Spec{Phase: phase.SpecPhase{ID: "p", Title: "t"}}
	body := BuildPRBody(spec, nil, sampleReviews())
	sec := body[strings.Index(body, "## Reviewer findings"):]
	for _, want := range []string{
		"- `t-2` — pass after 2 rounds",
		"  - **BLOCKING** spec `c-1` (round 1): pair skip untested — _fixed in the fix round_",
		"  - **FLAG** quality (round 1): long func — _non-blocking, left_",
		"- `t-10` — exhausted after 2 rounds: still blocked after the one fix round",
		"_unresolved — task failed_",
	} {
		if !strings.Contains(sec, want) {
			t.Errorf("reviewer section lacks %q:\n%s", want, sec)
		}
	}
	if strings.Index(sec, "`t-2`") > strings.Index(sec, "`t-10`") {
		t.Error("tasks are not in task order: t-2 must precede t-10")
	}
	if strings.Index(body, "## Reviewer findings") > strings.Index(body, "_Generated by `dross ship`") {
		t.Error("the reviewer section is not above the footer")
	}
}

func TestReviewSectionAbsentWithoutReviews(t *testing.T) {
	spec := &phase.Spec{Phase: phase.SpecPhase{ID: "p", Title: "t"}, Criteria: []phase.Criterion{{ID: "c-1", Text: "x"}}}
	base := BuildPRBody(spec, nil, nil)
	if got := BuildPRBody(spec, nil, map[string]changes.TaskReview{}); got != base {
		t.Error("an empty reviews map changed the body")
	}
	if strings.Contains(base, "Reviewer findings") {
		t.Error("a body with no reviews carries a reviewer section")
	}
}

func TestReviewSectionEscapes(t *testing.T) {
	r := map[string]changes.TaskReview{"t-1": {Outcome: "block|pass", Rounds: 1, Findings: []changes.ReviewFinding{
		{Round: 1, Kind: "quality", Severity: "FLAG", Text: "x\n## Fake heading", Resolution: "non-blocking, left"},
		{Round: 1, Kind: "quality", Severity: "NOTE", Text: "a|b", Resolution: "non-blocking, left"},
	}}}
	body := BuildPRBody(nil, nil, r)
	for _, line := range strings.Split(body, "\n") {
		if strings.HasPrefix(line, "## Fake") {
			t.Fatalf("finding text opened a heading:\n%s", body)
		}
	}
	if !strings.Contains(body, `a\|b`) || strings.Contains(body, "a|b") {
		t.Fatalf("a pipe in finding text is not escaped:\n%s", body)
	}
}

func TestReviewSectionCapped(t *testing.T) {
	big := strings.Repeat("y", 2048)
	var fs []changes.ReviewFinding
	for i := 0; i < 500; i++ {
		fs = append(fs, changes.ReviewFinding{Round: 1, Kind: "quality", Severity: "NOTE", Text: big, Resolution: "non-blocking, left"})
	}
	body := BuildPRBody(nil, nil, map[string]changes.TaskReview{"t-1": {Outcome: "pass", Rounds: 1, Findings: fs}})
	if len(body) > 60000 {
		t.Fatalf("body is %d chars, over 60,000", len(body))
	}
	shown := strings.Count(body, "  - **NOTE**")
	want := fmt.Sprintf("- … %d more findings in changes.json", 500-shown)
	if shown == 0 || !strings.Contains(body, want) {
		t.Fatalf("showed %d findings; tail %q missing:\n%s", shown, want, body[len(body)-300:])
	}
}

func TestReviewSectionStable(t *testing.T) {
	a := BuildPRBody(nil, nil, sampleReviews())
	b := BuildPRBody(nil, nil, sampleReviews())
	if a != b {
		t.Fatal("two renders of the same reviews differ")
	}
	if regexp.MustCompile(`\d{4}-\d{2}-\d{2}T`).MatchString(a) {
		t.Fatal("the body carries a timestamp")
	}
}
