package ship

import (
	"strings"
	"testing"

	"github.com/Rivil/dross/internal/phase"
	"github.com/Rivil/dross/internal/verify"
)

func TestBuildPRBodyFullArtefacts(t *testing.T) {
	spec := &phase.Spec{
		Phase: phase.SpecPhase{ID: "01-meal-tagging", Title: "Meal Tagging System"},
		Criteria: []phase.Criterion{
			{ID: "C1", Text: "Tags can be added to meals"},
			{ID: "C2", Text: "Tags can be filtered by | and color"},
		},
		Decisions: []phase.Decision{
			{Key: "storage", Choice: "drizzle JSON column", Why: "avoids join complexity", Locked: true},
		},
	}
	v := &verify.Verify{
		Verify: verify.VerifyMeta{Phase: "01-meal-tagging", Verdict: "pass"},
		Summary: verify.VerifySummary{
			MutationScore:     0.873,
			MutantsKilled:     123,
			MutantsSurvived:   18,
			CriteriaTotal:     2,
			CriteriaCovered:   2,
			CriteriaUncovered: 0,
		},
		Criteria: []verify.CriterionResult{
			{ID: "C1", Status: "covered", Tests: []string{"meal.test.ts:42"}},
			{ID: "C2", Status: "covered", Tests: []string{"meal.test.ts:78", "filter.test.ts:11"}},
		},
		Findings: []verify.Finding{
			{Severity: "NOTE", Text: "tag color picker UI is basic"},
			{Severity: "BLOCKING", Text: "shouldn't merge"},
			{Severity: "FLAG", Text: "review threshold magic number"},
		},
	}

	body := BuildPRBody(spec, v)

	for _, want := range []string{
		"# 01-meal-tagging — Meal Tagging System",
		"## Acceptance criteria",
		"| `C1` | Tags can be added to meals | covered | meal.test.ts:42 |",
		`Tags can be filtered by \| and color`, // pipe escaped
		"## Decisions locked",
		"- **storage** 🔒 — drizzle JSON column *(avoids join complexity)*",
		"## Efficacy",
		"Mutation score: **87.3%** (123 killed / 18 survived)",
		"Criteria coverage: **2/2** covered, 0 uncovered",
		"Verdict: **PASS**",
		"## Findings",
		"_Generated by `dross ship`",
	} {
		if !strings.Contains(body, want) {
			t.Errorf("expected %q in body\n--- body ---\n%s", want, body)
		}
	}

	// Findings ordered: BLOCKING before FLAG before NOTE.
	iBlock := strings.Index(body, "BLOCKING")
	iFlag := strings.Index(body, "FLAG")
	iNote := strings.Index(body, "NOTE")
	if !(iBlock < iFlag && iFlag < iNote) {
		t.Errorf("findings not severity-ordered: BLOCKING=%d FLAG=%d NOTE=%d", iBlock, iFlag, iNote)
	}
}

func TestBuildPRBodyMinimalSpec(t *testing.T) {
	spec := &phase.Spec{
		Phase: phase.SpecPhase{ID: "02-tiny", Title: "Tiny Phase"},
	}
	body := BuildPRBody(spec, nil)
	if !strings.Contains(body, "# 02-tiny — Tiny Phase") {
		t.Errorf("missing header: %s", body)
	}
	if strings.Contains(body, "## Acceptance criteria") {
		t.Errorf("should not show criteria section without criteria: %s", body)
	}
	if strings.Contains(body, "## Efficacy") {
		t.Errorf("should not show efficacy without verify: %s", body)
	}
}

func TestBuildPRBodyNilSpec(t *testing.T) {
	body := BuildPRBody(nil, nil)
	if !strings.Contains(body, "# phase") {
		t.Errorf("expected fallback header, got: %s", body)
	}
}

func TestBuildPRBodyHandlesUnverifiedCriterion(t *testing.T) {
	spec := &phase.Spec{
		Phase: phase.SpecPhase{ID: "03-x", Title: "X"},
		Criteria: []phase.Criterion{
			{ID: "C1", Text: "Should work"},
			{ID: "C2", Text: "Should also work"},
		},
	}
	v := &verify.Verify{
		Criteria: []verify.CriterionResult{
			{ID: "C1", Status: "covered", Tests: []string{"a.test.ts"}},
			// C2 has no result
		},
	}
	body := BuildPRBody(spec, v)
	// C2 row must render with placeholder status.
	if !strings.Contains(body, "| `C2` | Should also work | — | — |") {
		t.Errorf("expected placeholder for unverified C2, got:\n%s", body)
	}
}

func TestBuildPRBodyStableOutput(t *testing.T) {
	// Same input → same output (no timestamps embedded).
	spec := &phase.Spec{
		Phase:    phase.SpecPhase{ID: "01-x", Title: "X"},
		Criteria: []phase.Criterion{{ID: "C1", Text: "ok"}},
	}
	a := BuildPRBody(spec, nil)
	b := BuildPRBody(spec, nil)
	if a != b {
		t.Errorf("expected stable output:\nA: %s\nB: %s", a, b)
	}
}
